- name: Install System Packages 1 (build-essential)
  become: true
  apt:
    name: ["build-essential"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (unzip)
  become: true
  apt:
    name: [ "unzip" ]
  tags:
    - install
    - neovim
    - core

- name: Set lightdm as the default display manager
  become: true
  copy:
    content: /usr/sbin/lightdm 
    dest: "/etc/X11/default-display-manager"
    mode: '0644'

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: [ "curl", "htop", "sway", "nvidia-settings", "pavucontrol", "i3status", "wl-clipboard", "lightdm" ]
  tags:
    - install
    - core

      # - name: Reconfigure lightdm
      #   become: true
      #   command: dpkg-reconfigure lightdm -f noninteractive

- name: Set sway as default WM
  become: true
  copy:
    content: |
      [Seat:*]
      user-session=sway
    dest: "/etc/lightdm/lightdm.conf.d/50-sway.conf"
    mode: '0644'

