- name: Install System Packages 1 (build-essential)
  become: true
  apt:
    name: ["build-essential"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (unzip)
  become: true
  apt:
    name: [ "unzip" ]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: [ "curl", "htop", "sway", "nvidia-settings", "pavucontrol", "i3status", "wl-clipboard" ]
  tags:
    - install
    - core
- name: Install LightDM
  become: true
  apt:
    name: lightdm
  tags:
    - install
    - core

- name: Remove GDM3
  become: true
  apt:
    name: gdm3
    state: absent
  tags:
    - install
    - core

- name: Set sway as WM
  become: true
  copy:
    content: |
      [Seat:*]
      user-session=sway
    dest: "/etc/lightdm/lightdm.conf.d/50-sway.conf"
    mode: '0644'

