- name: Install System Packages 1 (build-essential)
  become: true
  apt:
    name: ["build-essential"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (unzip)
  become: true
  apt:
    name: [ "unzip" ]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: [ "curl", "htop",  "sway", "nvidia-settings", "pavucontrol" ]
  tags:
    - install
    - core

      # TODO: figure this out
      #- name: Ensure Sway session file exists for GDM
      #  become: true
      #  copy:
      #    dest: /usr/share/wayland-sessions/sway.desktop
      #    content: |
      #      [Desktop Entry]
      #      Name=Sway
      #      Exec=sway
      #      Type=Application
      #    mode: '0644'
      #
      #- name: Ensure Sway session file exists for GDM
      #  become: true
      #  copy:
      #    dest: "{{ ansible_env.HOME }}/.dmrc"
      #    content: |
      #      [Desktop]
      #      Session=sway
      #    mode: '0644'

